### ISSUE TITLE
Quadratic functions in the constraints are not picked up by MathOptNLPModel

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/NLPModelsJuMP.jl#173]
More specifically,

```julia
model = Model()
@variable(model, x[1:2])
@objective(model, Min, sum(x .^ 4))
@constraint(model, sum(x .^ 2) == 1)
nlp = MathOptNLPModel(model)
```

warns with

```
┌ Warning: Function MathOptInterface.ScalarQuadraticFunction{Float64} is not supported.
└ @ NLPModelsJuMP ~/.julia/packages/NLPModelsJuMP/1KSlI/src/utils.jl:219
```

And indeed, there are no constraints in the model. Solving the problem via JuMP using `NLPModels.Optimizer` works.

cc. @blegat, if you can help us again.

**Comment by blegat** [comment]
The `Optimizer` declares that quadratic functions are not supported through `supports_constraint` so JuMP bridges them to `ScalarNonlinearFunction` using https://jump.dev/MathOptInterface.jl/dev/submodules/Bridges/list_of_bridges/#MathOptInterface.Bridges.Constraint.ToScalarNonlinearBridge and these nonlinear functions are then handled correctly by `MathOptNLPModel`.

**Comment by tmigot** [comment]
I think we started some work on this with @amontoison a while ago https://github.com/JuliaSmoothOptimizers/NLPModelsJuMP.jl/pull/102

**Comment by abelsiqueira** [comment]
Just an update, related to #174, more general nonlinear constraints are also not supported

**Comment by abelsiqueira** [comment]
MWE:

```julia
using JuMP, NLPModelsJuMP, Percival
model = Model()
@variable(model, x[1:2])
@objective(model, Min, (x[1] - 1)^2 + 4 * (x[2] - x[1]^2)^2)
@constraint(model, x[1]^2 + x[2]^2 == 1)
@constraint(model, x[1]^4 + x[2]^4 == 1)
@constraint(model, x[1] * exp(x[2]) == 1)
nlp = MathOptNLPModel(model) # Warns Function MathOptInterface.ScalarQuadraticFunction{Float64} is not supported.
                             # And shows no constraints
output = percival(nlp) # Warns Problem does not have general constraints; calling tron
output.solution # Shows close to [1;1]
```

**Comment by amontoison** [comment]
@blegat @abelsiqueira 
Quadratic constraints with `@constraint` are now supported with the release 0.13.0 but general nonlinear constraints with `@constraint` are still not working.

I don't understand how they are stored because I don't have any error when create the MathOptNLPModel.

Don't we need to do something in this function [here](https://github.com/JuliaSmoothOptimizers/NLPModelsJuMP.jl/blob/main/src/utils.jl#L355-L426) for `ScalarNonLinearFunction` ?

**Comment by blegat** [comment]
You allow nonlinear functions thanks to
https://github.com/JuliaSmoothOptimizers/NLPModelsJuMP.jl/blob/3dd5054c3c774a4cbc887691964ab82632165ec4/src/utils.jl#L380C7-L380C39
but you don't do anything with it.
You are missing a `if typeof(fun) == MOI.ScalarNonlinearFunction` here
https://github.com/JuliaSmoothOptimizers/NLPModelsJuMP.jl/blob/3dd5054c3c774a4cbc887691964ab82632165ec4/src/utils.jl#L395-L410

**Comment by amontoison** [comment]
@blegat It's you that allowed nonlinear functions :wink: 
https://github.com/JuliaSmoothOptimizers/NLPModelsJuMP.jl/pull/171

**Comment by blegat** [comment]
Yes, indeed, I remember now. The current strategy is to put all the nonlinear function in the `NLPBlock` (see `_nlp_model`) since the `NLPBlock` is supported. So now throwing when we see these function is expected since we handle them later by adding them to the `NLPBlock`. If you add support for it natively, you can then stop adding them in the `NLPBlock`
